// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    mongo: {
      local: 'mongodb://localhost/bigscarylist',
      dev: 'mongodb://list:bigscary@oceanic.mongohq.com:10098/bigscarylist'
    }
  };

  module.exports = config;

}).call(this);
