// Generated by CoffeeScript 1.6.3
(function() {
  var app, config, express, mongoose, partials, port;

  config = require('./config');

  express = require('express');

  partials = require('express-partials');

  mongoose = require('mongoose');

  app = module.exports = express();

  app.configure('local', function() {
    return mongoose.connect(config.mongo.local);
  });

  app.configure('dev', function() {
    return mongoose.connect(config.mongo.dev);
  });

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(partials());
    app.use(express["static"](__dirname + '/public'));
    return app.use(app.router);
  });

  require("./routes/index")(app);

  port = process.env.PORT || 8000;

  app.listen(port, function() {
    return console.log('Weere Up!' + port);
  });

}).call(this);
